### ISSUE TITLE
Qonsole app not working through preprod gateway

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#12]
When a user clicks on the execute query button on the qonsole form, an http post is sent to:

  /app/root/qonsole/query

this is handled by the rails app which sends a request to

  {proto}://{origin-server}/landregistry/query

This normally works, but not in the case where the origin server is the preprod gateway.

The preprod gateway is a small nginx proxy that requires authentication in order to access the presentation server.  Qonsole does not attach an authentication header to its request, so the request is rejected by the preprod gateway.

Qonsole logs the error and returns a 200 response.

Qonsole does not currently have the credentials to attach an authentication header.

**Comment by ijdickinson** [comment]
@bwmcbride and I discussed design alternatives. For the short term, the deployment scripts are going to update the `qonfig.json` files to point to the non-public endpoint. 

Longer term, I will add either a mechanism for incorporating environment variables into `qonfig.json` files, or an 'include' mechanism, so that only part of the file (e.g. the endpoints) need be configured by the deployment scripts

**Comment by ijdickinson** [comment]
Migrated to the shared issue list https://github.com/epimorphics/hmlr-linked-data/issues/33
