### ISSUE TITLE
Welsh Accessibility and Privacy Statements behind broken links

### ISSUE THREAD

**Issue by tomguilbert** [epimorphics/lr-landing#130]
If you go to the English accessiblity or privacy statement pages via the footer and switch to welsh you get an error. The links:

https://landregistry.data.gov.uk/doc/accessibility?lang=cy
https://landregistry.data.gov.uk/doc/privacy?lang=cy

have an extra `doc/` in them and should be:

https://landregistry.data.gov.uk/accessibility?lang=cy
https://landregistry.data.gov.uk/privacy?lang=cy

**Comment by bogdanadrianmarc** [comment]
@tomguilbert This is now fixed in `dev` and will to go up to `preprod` and `production` together with the rest of the accessibility changes.

For testing this you can use the `dev` instance:
https://hmlr-dev-pres.epimorphics.net/

Now clicking on either accessibility or privacy links and changing the language should work. I think it's best for the ticket to remain in review and test again after release, just to make sure there's no regression

**Comment by tomguilbert** [comment]
Thanks @bogdanadrianmarc that does look to be working, but I agree we should retest in preprod and prod.

**Comment by tomguilbert** [comment]
Now this is in prod and looks fine so closing
